version: '3'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: musicfindr_dev
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: musicfindr_dev
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  pgdata:
